source 'http://rubygems.org'
#gem 'jquery-rails'
gem 'rails', '3.0.3'
gem 'mysql2'
gem "will_paginate", "3.0.pre"
gem 'authlogic', :git => 'git://github.com/odorcicd/authlogic.git',:branch => 'rails3'
gem 'meta_where'
gem 'pdfkit'
#gem "mongrel", '>= 1.2.0.pre2'
gem 'declarative_authorization'
gem 'fastercsv'
